### ISSUE TITLE
Not valid PROJECT ID when trigger action

### ISSUE THREAD

**Issue by anjopater** [jmaicaaan/tutorial-nextjs-cloud-run#1]
Hi, first of all, thanks you for you article, it is helping me a lot!

I 'm having this error when triggering the action. I have already my secrets in the project but still saying the same error.
<img width="1178" alt="image" src="https://user-images.githubusercontent.com/19295280/179371292-49b453b6-82d2-4235-b2b0-aae9901c7dc6.png">

<img width="1058" alt="image" src="https://user-images.githubusercontent.com/19295280/179371312-85626924-3ec2-4d2f-a698-9ecf81346219.png">

and I'm sharing the `.yml` file here also

```
name: project-name-cloud-run

on:
  push:
    branches:
      - master
      - main

env:
  PROJECT_ID: ${{ secrets.CLOUD_RUN_PROJECT_ID }}
  CLOUD_RUN_PROJECT_ID: ${{ secrets.CLOUD_RUN_PROJECT_NAME }}
  CLOUD_RUN_REGION: southamerica-east1
  # project-name but it can be anything you want
  REPO_NAME: project_frontend

jobs:
  build-and-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # This step is where our service account will be authenticated
      - uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.CLOUD_RUN_PROJECT_NAME }}
          service_account_key: ${{ secrets.CLOUD_RUN_SERVICE_ACCOUNT }}
          service_account_email: ${{ secrets.CLOUD_RUN_SERVICE_ACCOUNT_EMAIL }}

      - name: Enable the necessary APIs and enable docker auth
        run: |-
          gcloud services enable containerregistry.googleapis.com
          gcloud services enable run.googleapis.com
          gcloud --quiet auth configure-docker
      - name: Build and tag image
        run: |-
          docker build . --tag "gcr.io/$CLOUD_RUN_PROJECT_ID/$REPO_NAME:$GITHUB_SHA"
      - name: Push image to GCR
        run: |-
          docker push gcr.io/$CLOUD_RUN_PROJECT_ID/$REPO_NAME:$GITHUB_SHA
      - name: Deploy
        run: |-
          gcloud components install beta --quiet
          gcloud beta run deploy $REPO_NAME --image gcr.io/$CLOUD_RUN_PROJECT_ID/$REPO_NAME:$GITHUB_SHA \
            --project $CLOUD_RUN_PROJECT_ID \
            --platform managed \
            --region $CLOUD_RUN_REGION \
            --allow-unauthenticated \
            --quiet
```

The only difference here with your `.yml` file is I added this `PROJECT_ID: ${{ secrets.CLOUD_RUN_PROJECT_ID }}` to try to solve the problem but does not work. Can you help me, please?
